services:
  streamlit:
    container_name: mycve-streamlit
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      OLLAMA_BASE_URL: 'http://ollama:11434'
    ports:
      - "80:8501"
    volumes:
      - ./:/app
    working_dir: /app
    command: ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
    networks:
      - app_network

  ollama:
    image: ollama/ollama:latest
    volumes:
      - D:\ollama:/root/.ollama
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              count: all
              capabilities: [gpu]
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

#  ollama_data:
#    driver: local