from .get_robots_txt_with_requests import get_robots_txt_with_requests
from .get_robots_txt_with_selenium import get_robots_txt_with_selenium
from .get_robots_txt_with_playwright import get_robots_txt_with_playwright
from .get_robots_txt_with_undetected_chromedriver import get_robots_txt_with_undetected_chromedriver
